[package]
name = "mininn"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"

[dev-dependencies]
approx = "0.5.1"
