name: Deploy

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

env:
    CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install HDF5
      run: sudo apt update && sudo apt install -y libhdf5-dev
    - name: Tets
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --verbose --release
    - name: Docs Release
      run: cargo doc --release
  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Publish to Crates.io
        working-directory: /home/runner/work/mininn
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}