name: Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install HDF5
      run: sudo apt update && sudo apt install -y libhdf5-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
